version: '2'
services:
  eurekaserver:
    image:   immoapp/immo-eurekasvr:taxes
    ports:
      - "8761:8761"
  configserver:
    image: immoapp/immo-confsvr:taxes
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: 8761
      ENCRYPT_KEY:       "IMSYMMETRIC"
  gateservice:
    image: immoapp/immo-gate:taxes
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ORGSERVERNEW_PORT:        "8087"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=eagle_eye_local
  optimisationfiscaleservice:
    image: immoapp/optimisation-fiscale-service:taxes
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ORGSERVERNEW_PORT:        "8087"
      ZUULSERVER_PORT:          "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  produitimmobilierservice:
    image: immoapp/produit-immobilier-service:taxes
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ORGSERVERNEW_PORT:        "8087"
      ZUULSERVER_PORT:          "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  auditservice:
    image: immoapp/audit-service:taxes
    ports:
      - "9191:9191"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ORGSERVERNEW_PORT:        "8087"
      ZUULSERVER_PORT:          "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  specialroutes-service:
    image: immoapp/specialroutes-service:taxes
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"













