version: '2'
services:
  eurekaserver:
    image: 984907864453.dkr.ecr.eu-west-3.amazonaws.com/immo-eurekasvr:immo-eurekasvr
    mem_limit: 1073741824
    ports:
      - "8761:8761"
  configserver:
    image: immoapp/immo-confsvr:taxes
    mem_limit: 1073741824
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  gateservice:
    image: 984907864453.dkr.ecr.eu-west-3.amazonaws.com/immo-gate:immo-gate
    mem_limit: 1073741824
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      AUDIT_PORT:               "8087"
      DB_PORT:                  "8930"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Esprit292948
      - POSTGRES_DB=immo_db_local
  optimisationfiscaleservice:
    image: 984907864453.dkr.ecr.eu-west-3.amazonaws.com/optimisation-fiscale-service:optimisation-fiscale-service
    mem_limit: 1073741824
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      AUDIT_PORT:               "8087"
      ZUULSERVER_PORT:          "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  produitimmobilierservice:
    image: 984907864453.dkr.ecr.eu-west-3.amazonaws.com/produit-immobilier-service:produit-immobilier-service
    mem_limit: 1073741824
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      AUDIT_PORT:               "8087"
      ZUULSERVER_PORT:          "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  auditservice:
    image: 984907864453.dkr.ecr.eu-west-3.amazonaws.com/audit-service:audit-service
    mem_limit: 1073741824
    ports:
      - "8087:8087"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8087"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      PRODUITIMMOBILIER_PORT:   "8085"
      DB_PORT:                  "8930"
      ZUULSERVER_PORT:          "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  specialroutes-service:
    image: 984907864453.dkr.ecr.eu-west-3.amazonaws.com/specialroutes-service:specialroutes-service
    mem_limit: 1073741824
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  db-service:
    image: 984907864453.dkr.ecr.eu-west-3.amazonaws.com/db-service:db-service
    mem_limit: 1073741824
    ports:
      - "8930:8930"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8930"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ZUULSERVER_PORT:          "5555"
      ENCRYPT_KEY:       "IMSYMMETRIC"













