CREATE TABLE IF NOT EXISTS PRODUIT_IMMOBILIER
(
    ID integer NOT NULL,
    TYPE character varying(100) COLLATE pg_catalog."default",
    TELEPHONE character varying(50) COLLATE pg_catalog."default",
    NOMBRE_LOTS smallint,
    PARKING boolean,
    ASCENCEUR boolean,
    DPE "char",
    CHARGES_COPROP numeric,
    TAXES_FONCIAIRES character varying COLLATE pg_catalog."default",
    ANNEE_CONSTRUCTION date,
    ADRESSE character varying(250) COLLATE pg_catalog."default",
    PRIX numeric,
    SURFACE double precision,
    SURFACE_BALCON double precision,
    SURFACE_TERRASSE double precision,
    SURFACE_VERANDAS double precision,
    SURFACE_SOUS_SOL double precision,
    SURFACE_CAVE double precision,
    SURFACE_LOGIAS double precision,
    AUTRE_SURFACE_ANNEXE double precision,
    CONSTRAINT "PRODUIT_IMMOBILIER_pkey" PRIMARY KEY (ID)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE PRODUIT_IMMOBILIER
    OWNER to postgres;

commit;

INSERT INTO PRODUIT_IMMOBILIER (ID ,  TYPE, TELEPHONE, NOMBRE_LOTS, PARKING, ASCENCEUR , DPE , CHARGES_COPROP , TAXES_FONCIAIRES, ANNEE_CONSTRUCTION , ADRESSE ,PRIX, SURFACE, SURFACE_BALCON,SURFACE_TERRASSE, SURFACE_VERANDAS, SURFACE_SOUS_SOL, SURFACE_CAVE, SURFACE_LOGIAS, AUTRE_SURFACE_ANNEXE)
VALUES (1, 'APPARTEMENT NEUF', '065646847',3,TRUE, TRUE,'A',4300,'11%','01-01-2020', 'VILLEJUIF', 250000, 54, 6, 4 , null , null, 4 , 6, null)
ON CONFLICT (ID) DO NOTHING;

INSERT INTO PRODUIT_IMMOBILIER (ID ,  TYPE, TELEPHONE, NOMBRE_LOTS, PARKING, ASCENCEUR , DPE , CHARGES_COPROP , TAXES_FONCIAIRES, ANNEE_CONSTRUCTION , ADRESSE , PRIX, SURFACE, SURFACE_BALCON,SURFACE_TERRASSE, SURFACE_VERANDAS, SURFACE_SOUS_SOL, SURFACE_CAVE, SURFACE_LOGIAS, AUTRE_SURFACE_ANNEXE)
VALUES (2, 'APPARTEMENT NEUF', '074538470',2,TRUE, TRUE,'A',3800,'11%','01-01-2021', 'NOISY LE GRAND', 265000, 72, 4, 4 , null , null, 2 , 4 , null)
ON CONFLICT (ID) DO NOTHING;
