server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/mkhemir/config-repo/
          searchPaths: dbservice #,produitimmobilierservice
          username: marwen.kemir@gmail.com
          password: Esprit292948